server:
  port: 8080
#  servlet:
#    context-path: /

spring:
  main:
    web-application-type: reactive
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: microservice-gateway

  cloud:
    gateway:
      routes:
        # Microservicio Reservations
        - id: reservation-service
          uri: lb://RESERVATIONMS
          predicates:
            - Path=/reservations/**
          filters:
            - RewritePath=/reservations/(?<segment>.*), /api/v1/${segment}

#        - id: payments
#          uri: http://localhost:8082
#          predicates:
#            - Path=/apirest-payments/invoices/**
#          filters:
#            - StripPrefix=1
#            - name: AuthenticationFilter

        # Microservicio Payments
        #Cambien para sus microservicios
        # Microservicio Users
        - id: users
          uri: lb://USER-MICROSERVICE
          predicates:
            - Path=/users/**
            - Path=/auth/**
          filters:
            - RewritePath=/users/(?<segment>.*), /api/v1/${segment}
            - RewritePath=/auth/(?<segment>.*), /api/v1/${segment}

#        - id: user-microservice
#          uri: http://localhost:8084
#          predicates:
#            - Path=/auth/**
#          filters:
#            - StripPrefix=0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG

app:
  jwt:
    secret: m1Cl4v3S3cr3t4MuyLarg4yC0mplej4ParaJWT1234567890x
    expiration:
      duration: 3600000

management:
  endpoint:
    health:
      show-details: always
  health:
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info